### ISSUE TITLE
How to change the size

### ISSUE THREAD

**Issue by skuppa** [werthdavid/ngx-zxing#4]
The angular component works great but I am not able to resize.  I even tried in the plunker but did not work.  Is that possible to resize and can you show me an example?

Thanks.

**Comment by Timothee-Retailleau** [comment]
you can resize with your host component css with ng-deep

```
::ng-deep video {
    max-height: 70vh;
    width: 100vw;
    object-fit: contain;
}
```

**Comment by skuppa** [comment]
Thank you very much.  It works great.

**Comment by werthdavid** [comment]
Thanks for the help Timothee.
Will probably make an Input so you can pass an extra css-class do avoid using /deep/....

**Comment by FvelascoDS** [comment]
Hi there!
I've seen that this issue is closed, however let me comment a couple of things.
I'm using this package in an Ionic/Angular app. I've been experiencing the same problem with the video size. I added [cssClass] ="small-Video" and its respective class in the css file, but nothing changed.
I checked my ngx-zxing version, it's the last version until now, 0.3.4.
After inspecting the "preview" element in the browser I realized that the resulting html code for this element might be wrong; indeed the class name was empty or its value is "NaN" (I got two versions...):

Version 1:
<ngx-zxing ng-reflect-start="true" ng-reflect-css- ng-reflect-device="[object Object]">
<div class="form">
<video id="preview" **class** autoplay="true" muted="true" playsinline="true" autofocus="true"></video>
</div>
</ngx-zxing>

Version 2:
<ngx-zxing ng-reflect-start="true" ng-reflect-css- ng-reflect-device="[object Object]">
<div class="form">
<video id="preview" **class=NaN** autoplay="true" muted="true" playsinline="true" autofocus="true"></video>
</div>
</ngx-zxing>


------------------

I solved this adding the same class afterwards through js code:
document.getElementById("preview").className = "small-Video";

Thanks for your great work.

**Comment by werthdavid** [comment]
Will check on that

**Comment by werthdavid** [comment]
Just looked at your example... It seems like your binding is wrong.
Please try either
[cssClass]="'small-video'" 
or
cssClass="small-video"

I will update the Readme
